apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 039430993388.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 039430993388.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: d7ad2e11
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
